// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: iicpc/v1/services.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- Basic Request/Response Payloads ---
type SubmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContestantId  string                 `protobuf:"bytes,1,opt,name=contestant_id,json=contestantId,proto3" json:"contestant_id,omitempty"`
	ArtifactUrl   string                 `protobuf:"bytes,2,opt,name=artifact_url,json=artifactUrl,proto3" json:"artifact_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_iicpc_v1_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iicpc_v1_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_iicpc_v1_services_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitRequest) GetContestantId() string {
	if x != nil {
		return x.ContestantId
	}
	return ""
}

func (x *SubmitRequest) GetArtifactUrl() string {
	if x != nil {
		return x.ArtifactUrl
	}
	return ""
}

type SubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_iicpc_v1_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iicpc_v1_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_iicpc_v1_services_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_iicpc_v1_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iicpc_v1_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_iicpc_v1_services_proto_rawDescGZIP(), []int{2}
}

func (x *StatusRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_iicpc_v1_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iicpc_v1_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_iicpc_v1_services_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type DeployRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ImageRef      string                 `protobuf:"bytes,2,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	mi := &file_iicpc_v1_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iicpc_v1_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_iicpc_v1_services_proto_rawDescGZIP(), []int{4}
}

func (x *DeployRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *DeployRequest) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

type DeployResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PodIp         string                 `protobuf:"bytes,2,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployResponse) Reset() {
	*x = DeployResponse{}
	mi := &file_iicpc_v1_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResponse) ProtoMessage() {}

func (x *DeployResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iicpc_v1_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResponse.ProtoReflect.Descriptor instead.
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return file_iicpc_v1_services_proto_rawDescGZIP(), []int{5}
}

func (x *DeployResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeployResponse) GetPodIp() string {
	if x != nil {
		return x.PodIp
	}
	return ""
}

type TeardownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeardownRequest) Reset() {
	*x = TeardownRequest{}
	mi := &file_iicpc_v1_services_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeardownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeardownRequest) ProtoMessage() {}

func (x *TeardownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iicpc_v1_services_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeardownRequest.ProtoReflect.Descriptor instead.
func (*TeardownRequest) Descriptor() ([]byte, []int) {
	return file_iicpc_v1_services_proto_rawDescGZIP(), []int{6}
}

func (x *TeardownRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type TeardownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeardownResponse) Reset() {
	*x = TeardownResponse{}
	mi := &file_iicpc_v1_services_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeardownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeardownResponse) ProtoMessage() {}

func (x *TeardownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iicpc_v1_services_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeardownResponse.ProtoReflect.Descriptor instead.
func (*TeardownResponse) Descriptor() ([]byte, []int) {
	return file_iicpc_v1_services_proto_rawDescGZIP(), []int{7}
}

func (x *TeardownResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StartLoadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TargetIp      string                 `protobuf:"bytes,2,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
	DurationSec   int32                  `protobuf:"varint,3,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartLoadRequest) Reset() {
	*x = StartLoadRequest{}
	mi := &file_iicpc_v1_services_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLoadRequest) ProtoMessage() {}

func (x *StartLoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iicpc_v1_services_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLoadRequest.ProtoReflect.Descriptor instead.
func (*StartLoadRequest) Descriptor() ([]byte, []int) {
	return file_iicpc_v1_services_proto_rawDescGZIP(), []int{8}
}

func (x *StartLoadRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StartLoadRequest) GetTargetIp() string {
	if x != nil {
		return x.TargetIp
	}
	return ""
}

func (x *StartLoadRequest) GetDurationSec() int32 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

type StartLoadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartLoadResponse) Reset() {
	*x = StartLoadResponse{}
	mi := &file_iicpc_v1_services_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLoadResponse) ProtoMessage() {}

func (x *StartLoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iicpc_v1_services_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLoadResponse.ProtoReflect.Descriptor instead.
func (*StartLoadResponse) Descriptor() ([]byte, []int) {
	return file_iicpc_v1_services_proto_rawDescGZIP(), []int{9}
}

func (x *StartLoadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StopLoadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopLoadRequest) Reset() {
	*x = StopLoadRequest{}
	mi := &file_iicpc_v1_services_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopLoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopLoadRequest) ProtoMessage() {}

func (x *StopLoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iicpc_v1_services_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopLoadRequest.ProtoReflect.Descriptor instead.
func (*StopLoadRequest) Descriptor() ([]byte, []int) {
	return file_iicpc_v1_services_proto_rawDescGZIP(), []int{10}
}

func (x *StopLoadRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type StopLoadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopLoadResponse) Reset() {
	*x = StopLoadResponse{}
	mi := &file_iicpc_v1_services_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopLoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopLoadResponse) ProtoMessage() {}

func (x *StopLoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iicpc_v1_services_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopLoadResponse.ProtoReflect.Descriptor instead.
func (*StopLoadResponse) Descriptor() ([]byte, []int) {
	return file_iicpc_v1_services_proto_rawDescGZIP(), []int{11}
}

func (x *StopLoadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_iicpc_v1_services_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iicpc_v1_services_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_iicpc_v1_services_proto_rawDescGZIP(), []int{12}
}

func (x *IngestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardRequest) Reset() {
	*x = LeaderboardRequest{}
	mi := &file_iicpc_v1_services_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardRequest) ProtoMessage() {}

func (x *LeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iicpc_v1_services_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardRequest.ProtoReflect.Descriptor instead.
func (*LeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_iicpc_v1_services_proto_rawDescGZIP(), []int{13}
}

func (x *LeaderboardRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type LeaderboardResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RankedContestants []string               `protobuf:"bytes,1,rep,name=ranked_contestants,json=rankedContestants,proto3" json:"ranked_contestants,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LeaderboardResponse) Reset() {
	*x = LeaderboardResponse{}
	mi := &file_iicpc_v1_services_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardResponse) ProtoMessage() {}

func (x *LeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iicpc_v1_services_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardResponse.ProtoReflect.Descriptor instead.
func (*LeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_iicpc_v1_services_proto_rawDescGZIP(), []int{14}
}

func (x *LeaderboardResponse) GetRankedContestants() []string {
	if x != nil {
		return x.RankedContestants
	}
	return nil
}

var File_iicpc_v1_services_proto protoreflect.FileDescriptor

const file_iicpc_v1_services_proto_rawDesc = "" +
	"\n" +
	"\x17iicpc/v1/services.proto\x12\biicpc.v1\x1a\x17iicpc/v1/messages.proto\"W\n" +
	"\rSubmitRequest\x12#\n" +
	"\rcontestant_id\x18\x01 \x01(\tR\fcontestantId\x12!\n" +
	"\fartifact_url\x18\x02 \x01(\tR\vartifactUrl\"'\n" +
	"\x0eSubmitResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"&\n" +
	"\rStatusRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"&\n" +
	"\x0eStatusResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\"C\n" +
	"\rDeployRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n" +
	"\timage_ref\x18\x02 \x01(\tR\bimageRef\"A\n" +
	"\x0eDeployResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x15\n" +
	"\x06pod_ip\x18\x02 \x01(\tR\x05podIp\"(\n" +
	"\x0fTeardownRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\",\n" +
	"\x10TeardownResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"i\n" +
	"\x10StartLoadRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n" +
	"\ttarget_ip\x18\x02 \x01(\tR\btargetIp\x12!\n" +
	"\fduration_sec\x18\x03 \x01(\x05R\vdurationSec\"-\n" +
	"\x11StartLoadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"(\n" +
	"\x0fStopLoadRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\",\n" +
	"\x10StopLoadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"*\n" +
	"\x0eIngestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"*\n" +
	"\x12LeaderboardRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"D\n" +
	"\x13LeaderboardResponse\x12-\n" +
	"\x12ranked_contestants\x18\x01 \x03(\tR\x11rankedContestants2\x94\x01\n" +
	"\fOrchestrator\x12A\n" +
	"\fSubmitEngine\x12\x17.iicpc.v1.SubmitRequest\x1a\x18.iicpc.v1.SubmitResponse\x12A\n" +
	"\fGetRunStatus\x12\x17.iicpc.v1.StatusRequest\x1a\x18.iicpc.v1.StatusResponse2\x9f\x01\n" +
	"\x0fSandboxDeployer\x12B\n" +
	"\rDeploySandbox\x12\x17.iicpc.v1.DeployRequest\x1a\x18.iicpc.v1.DeployResponse\x12H\n" +
	"\x0fTeardownSandbox\x12\x19.iicpc.v1.TeardownRequest\x1a\x1a.iicpc.v1.TeardownResponse2\x98\x01\n" +
	"\rBotController\x12D\n" +
	"\tStartLoad\x12\x1a.iicpc.v1.StartLoadRequest\x1a\x1b.iicpc.v1.StartLoadResponse\x12A\n" +
	"\bStopLoad\x12\x19.iicpc.v1.StopLoadRequest\x1a\x1a.iicpc.v1.StopLoadResponse2N\n" +
	"\bIngester\x12B\n" +
	"\x0fStreamTelemetry\x12\x13.iicpc.v1.Telemetry\x1a\x18.iicpc.v1.IngestResponse(\x012\\\n" +
	"\aScoring\x12Q\n" +
	"\x12GetLiveLeaderboard\x12\x1c.iicpc.v1.LeaderboardRequest\x1a\x1d.iicpc.v1.LeaderboardResponseB9Z7github.com/YOUR_USERNAME/iicpc-platform-2026/schemas/v1b\x06proto3"

var (
	file_iicpc_v1_services_proto_rawDescOnce sync.Once
	file_iicpc_v1_services_proto_rawDescData []byte
)

func file_iicpc_v1_services_proto_rawDescGZIP() []byte {
	file_iicpc_v1_services_proto_rawDescOnce.Do(func() {
		file_iicpc_v1_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iicpc_v1_services_proto_rawDesc), len(file_iicpc_v1_services_proto_rawDesc)))
	})
	return file_iicpc_v1_services_proto_rawDescData
}

var file_iicpc_v1_services_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_iicpc_v1_services_proto_goTypes = []any{
	(*SubmitRequest)(nil),       // 0: iicpc.v1.SubmitRequest
	(*SubmitResponse)(nil),      // 1: iicpc.v1.SubmitResponse
	(*StatusRequest)(nil),       // 2: iicpc.v1.StatusRequest
	(*StatusResponse)(nil),      // 3: iicpc.v1.StatusResponse
	(*DeployRequest)(nil),       // 4: iicpc.v1.DeployRequest
	(*DeployResponse)(nil),      // 5: iicpc.v1.DeployResponse
	(*TeardownRequest)(nil),     // 6: iicpc.v1.TeardownRequest
	(*TeardownResponse)(nil),    // 7: iicpc.v1.TeardownResponse
	(*StartLoadRequest)(nil),    // 8: iicpc.v1.StartLoadRequest
	(*StartLoadResponse)(nil),   // 9: iicpc.v1.StartLoadResponse
	(*StopLoadRequest)(nil),     // 10: iicpc.v1.StopLoadRequest
	(*StopLoadResponse)(nil),    // 11: iicpc.v1.StopLoadResponse
	(*IngestResponse)(nil),      // 12: iicpc.v1.IngestResponse
	(*LeaderboardRequest)(nil),  // 13: iicpc.v1.LeaderboardRequest
	(*LeaderboardResponse)(nil), // 14: iicpc.v1.LeaderboardResponse
	(*Telemetry)(nil),           // 15: iicpc.v1.Telemetry
}
var file_iicpc_v1_services_proto_depIdxs = []int32{
	0,  // 0: iicpc.v1.Orchestrator.SubmitEngine:input_type -> iicpc.v1.SubmitRequest
	2,  // 1: iicpc.v1.Orchestrator.GetRunStatus:input_type -> iicpc.v1.StatusRequest
	4,  // 2: iicpc.v1.SandboxDeployer.DeploySandbox:input_type -> iicpc.v1.DeployRequest
	6,  // 3: iicpc.v1.SandboxDeployer.TeardownSandbox:input_type -> iicpc.v1.TeardownRequest
	8,  // 4: iicpc.v1.BotController.StartLoad:input_type -> iicpc.v1.StartLoadRequest
	10, // 5: iicpc.v1.BotController.StopLoad:input_type -> iicpc.v1.StopLoadRequest
	15, // 6: iicpc.v1.Ingester.StreamTelemetry:input_type -> iicpc.v1.Telemetry
	13, // 7: iicpc.v1.Scoring.GetLiveLeaderboard:input_type -> iicpc.v1.LeaderboardRequest
	1,  // 8: iicpc.v1.Orchestrator.SubmitEngine:output_type -> iicpc.v1.SubmitResponse
	3,  // 9: iicpc.v1.Orchestrator.GetRunStatus:output_type -> iicpc.v1.StatusResponse
	5,  // 10: iicpc.v1.SandboxDeployer.DeploySandbox:output_type -> iicpc.v1.DeployResponse
	7,  // 11: iicpc.v1.SandboxDeployer.TeardownSandbox:output_type -> iicpc.v1.TeardownResponse
	9,  // 12: iicpc.v1.BotController.StartLoad:output_type -> iicpc.v1.StartLoadResponse
	11, // 13: iicpc.v1.BotController.StopLoad:output_type -> iicpc.v1.StopLoadResponse
	12, // 14: iicpc.v1.Ingester.StreamTelemetry:output_type -> iicpc.v1.IngestResponse
	14, // 15: iicpc.v1.Scoring.GetLiveLeaderboard:output_type -> iicpc.v1.LeaderboardResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_iicpc_v1_services_proto_init() }
func file_iicpc_v1_services_proto_init() {
	if File_iicpc_v1_services_proto != nil {
		return
	}
	file_iicpc_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iicpc_v1_services_proto_rawDesc), len(file_iicpc_v1_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_iicpc_v1_services_proto_goTypes,
		DependencyIndexes: file_iicpc_v1_services_proto_depIdxs,
		MessageInfos:      file_iicpc_v1_services_proto_msgTypes,
	}.Build()
	File_iicpc_v1_services_proto = out.File
	file_iicpc_v1_services_proto_goTypes = nil
	file_iicpc_v1_services_proto_depIdxs = nil
}
